import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/sections/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "surface-dim": "#131313",
        "on-primary-container": "#757575",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-highest": "#353535",
        "outline-variant": "#4c4546",
        "inverse-primary": "#5e5e5e",
        "surface-tint": "#c6c6c6",
        "on-secondary-container": "#b4b5b5",
        "surface-container": "#1f1f1f",
        "on-secondary": "#2f3131",
        "on-error": "#690005",
        "primary-container": "#000000",
        tertiary: "#c6c6c6",
        primary: "#c6c6c6",
        "on-secondary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-fixed": "#1b1b1b",
        "secondary-container": "#454747",
        "on-tertiary-container": "#757575",
        "inverse-on-surface": "#303030",
        "on-surface": "#e2e2e2",
        outline: "#988e90",
        "on-background": "#e2e2e2",
        "surface-bright": "#393939",
        "surface-variant": "#353535",
        "surface-container-low": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "surface-container-lowest": "#0e0e0e",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-high": "#2a2a2a",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary": "#303030",
        "on-tertiary": "#303030",
        background: "#131313",
        "on-surface-variant": "#cfc4c5",
        "inverse-surface": "#e2e2e2",
        "tertiary-container": "#000000",
        "error-container": "#93000a",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "secondary-fixed-dim": "#c6c6c7",
        secondary: "#c6c6c7",
        surface: "#131313",
        "galaxy-blue": "#0A84FF",
        "galaxy-blue-dim": "rgba(10, 132, 255, 0.15)",
      },
      borderRadius: {
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      spacing: {
        "container-max": "1280px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-mobile": "20px",
        "stack-md": "16px",
        "section-gap": "160px",
        "stack-sm": "8px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "sans-serif"],
        display: ["var(--font-display)", "sans-serif"],
        "display-2xl-mobile": ["var(--font-display)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-display)", "sans-serif"],
        "display-2xl": ["var(--font-display)", "sans-serif"],
        "headline-lg": ["var(--font-display)", "sans-serif"],
        "body-md": ["var(--font-sans)", "sans-serif"],
        "label-sm": ["var(--font-sans)", "sans-serif"],
      },
      fontSize: {
        "display-2xl-mobile": [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "headline-lg-mobile": [
          "32px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "display-2xl": [
          "72px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.04em",
            fontWeight: "800",
          },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "18px",
          {
            lineHeight: "1.6",
            letterSpacing: "0",
            fontWeight: "400",
          },
        ],
        "label-sm": [
          "14px",
          {
            lineHeight: "1",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};

export default config;
